### ISSUE TITLE
Password problem 

### ISSUE THREAD

**Issue by nazim104** [pitube08642/Fluxion-on-ESP8266#1]
M1z23r (deauther) wrong password problem.  I have tried uninstalling and reinstalling the program to resolve this issue but still encountering the same issue.Please let me know if you know the solution
![IMG_20240321_195420](https://github.com/pitube08642/Fluxion-on-ESP8266/assets/164360039/b048f2d3-3e1c-4db7-bc6d-fc58bf7c8374)

**Comment by pitube08642** [comment]
Password is "deauther".
